### Register User
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "nama": "Guru 1",
  "username": "guru",
  "password": "password123"
}

### Login User
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "guru",
  "password": "password123"
}

### Forgot Password
POST http://localhost:3000/api/auth/forgot-password
Content-Type: application/json

{
  "username": "guru"
}
