@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhM2ZlZjliMS1hMzdmLTQ5ODgtYjNlMC1jY2RkNDVlN2M5OTIiLCJpYXQiOjE3MzkzMzUyNjEsImV4cCI6MTczOTMzODg2MX0.61hHBqWeAmbSdQWrAlJeET5EgudoWoPXQuYWkRyUpj4
###
POST http://localhost:3000/api/setoran
Content-Type: application/json
# Authorization: Bearer {{token}}

{
  "tema": "Belajar Bahasa Arab",
  "deskripsi": "al-qiraah",
}